services:
  pcb-frontend:
    container_name: pcb-landing-page
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      # KUNCI KEAMANAN: Bind ke localhost agar tidak terekspos publik
      - "127.0.0.1:8080:80"
    restart: unless-stopped
    networks:
      - pcb-network
      # Daftarkan ke network NPM agar bisa di-routing
      - api-pcb_iot_network

networks:
  pcb-network:
    driver: bridge
  # Deklarasikan network eksternal
  api-pcb_iot_network:
    external: true